### PR TITLE
increased the total retries to 450 from 10.

### PR DESCRIPTION
**Pull request by eoliveros**
currently emails are generated every 4 minutes to report there's a problem.

4 * 60 = 240sec
retries =10

240/10 = 24seconds per retry
so an attempt is made every 24 seconds and when failed it generates the emails.

60 * 60 * 3 = 10800seconds
if it retries every 24 seconds:
```
10800 / 24 = 450(retries)
```

### CODE REVIEW

**Comment by djpnewton** [comment]
I think we should start with something more conservative like 20

**Comment by eoliveros** [comment]
cool, so if its still fails after 20 tries it alarms? if my calculation is correct, considering the 10 tries appears to generate an email approximately 4 minutes, should now appear every 8 minutes when its changed.

**Comment by djpnewton** [comment]
I dont think the math works like you think

there is a backoff factor (look at the Retry documentation)

**Comment by eoliveros** [comment]
considering there was an issue with testnet.zap.me and has the sender as mainnet.zap.me, do you still need this PR? or can it be close?

**Comment by djpnewton** [comment]
yeah we can close

**Pull request closed without merging**
